### ISSUE TITLE
Обновить зависимости

### ISSUE THREAD

**Issue by maxkol** [maxkol/Rushandball.Online#2]
- [ ] + PrimeNg
- [ ] - FontAwesome 4
- [ ] + FontAwesome Pro 5
- [ ] - famfamfam flags
- [ ] + svg flags

**Comment by kurbala** [comment]
> * [ ]  + PrimeNg
> * [ ]  - FontAwesome 4
> * [ ]  + FontAwesome Pro 5
> * [ ]  - famfamfam flags
> * [ ]  + svg flags
